apiVersion: v1
kind: Service
metadata:
  name: booknest-service
spec:
  selector:
    app: booknest-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001  
  type: ClusterIP
